import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import AmplifyProvider from "@/components/AmplifyProvider";
import Navbar from "@/components/global/Navbar";
import Sidebar from "@/components/global/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AmplifyProvider>
          <main className="">
            <Navbar />
            <div className="pl-[250px] relative">
              <Sidebar />
              <main className="p-4">{children}</main>
            </div>
          </main>
        </AmplifyProvider>
      </body>
    </html>
  );
}
