import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import AmplifyProvider from "@/components/AmplifyProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AmplifyProvider>
          <main className="">{children}</main>
        </AmplifyProvider>
      </body>
    </html>
  );
}
